# Generated by Django 5.2.5 on 2025-09-09 15:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
        ('vehiculos', '0003_alter_vehiculo_dominio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('simbolo', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name': 'Divisa',
                'verbose_name_plural': 'Divisas',
                'db_table': 'tablaDivias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, help_text='Fecha del viaje.')),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('valor_flete', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('viaticos', models.DecimalField(decimal_places=2, help_text='Porcentaje de viáticos (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('gasto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ganancia_total', models.DecimalField(decimal_places=2, help_text='Se calcula automáticamente al guardar.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_destino', to='ubicaciones.localidad')),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='viajes.divisa')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_salida', to='ubicaciones.localidad')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'db_table': 'tablaViajes',
                'ordering': ['-fecha', '-creado_en'],
                'indexes': [models.Index(fields=['vehiculo'], name='tablaViajes_vehicul_bd8a0e_idx'), models.Index(fields=['salida'], name='tablaViajes_salida__7e2d38_idx'), models.Index(fields=['destino'], name='tablaViajes_destino_6309fc_idx'), models.Index(fields=['fecha'], name='tablaViajes_fecha_bb206e_idx')],
            },
        ),
    ]
