# Generated by Django 5.2.5 on 2025-09-11 14:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='porcentaje_conductor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje del flete para el conductor (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viaje',
            name='viaticos',
            field=models.DecimalField(decimal_places=2, help_text='Monto de viáticos (no porcentaje).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
