# Generated by Django 5.2.5 on 2025-09-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_viaje_porcentaje_conductor_alter_viaje_viaticos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='divisa',
            table='tablaDivisa',
        ),
    ]
