# Generated by Django 5.2.5 on 2025-09-12 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_options_remove_cliente_divisa_and_more'),
        ('ubicaciones', '0001_initial'),
        ('vehiculos', '0003_alter_vehiculo_dominio_and_more'),
        ('viajes', '0003_alter_divisa_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='clientes.cliente'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['cliente'], name='tablaViajes_cliente_157873_idx'),
        ),
    ]
