# Generated by Django 5.2.5 on 2025-09-22 14:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_viaje_cliente_viaje_tablaviajes_cliente_157873_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='gasto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suma automática de todos los gastos extra del viaje.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='GastoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_extra', to='viajes.viaje')),
            ],
            options={
                'db_table': 'tablaGastosExtra',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
