# Generated by Django 5.2.5 on 2025-09-22 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_ejes'),
        ('viajes', '0005_alter_viaje_gasto_gastoextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='vehiculos.vehiculo'),
        ),
    ]
