# Generated by Django 5.2.5 on 2025-10-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_alter_viaje_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha',
            field=models.DateTimeField(db_index=True, help_text='Fecha y hora del viaje.'),
        ),
    ]
