# Generated by Django 5.2.5 on 2025-08-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60, verbose_name='Marca')),
                ('dominio', models.CharField(help_text='AA123BB o ABC123', max_length=10, unique=True, verbose_name='Dominio')),
                ('modelo', models.CharField(max_length=60, verbose_name='Modelo')),
                ('dominio_remolque', models.CharField(blank=True, help_text='Opcional. AA123BB o ABC123', max_length=10, null=True, unique=True, verbose_name='Dominio remolque')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'tablaVehiculos',
                'ordering': ['id'],
            },
        ),
    ]
