# Generated by Django 5.2.5 on 2025-08-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio_fabricacion', models.PositiveIntegerField(verbose_name='Año de Fabricación')),
                ('dominio', models.CharField(max_length=10, unique=True)),
                ('dominio_remolque', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'tablaVehiculos',
            },
        ),
    ]
