# Generated by Django 5.2.5 on 2025-08-31 12:22

import django.core.validators
import vehiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveSmallIntegerField(default=2013, help_text='Año de fabricación', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(vehiculos.models.max_year)], verbose_name='Año'),
            preserve_default=False,
        ),
    ]
