# Generated by Django 5.2.5 on 2025-09-02 13:15

import django.core.validators
import vehiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['id'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio_fabricacion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(vehiculos.models.current_year)], verbose_name='Año de fabricación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='dominio',
            field=models.CharField(max_length=10, unique=True, verbose_name='Dominio'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='dominio_remolque',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dominio del remolque'),
        ),
    ]
