# Generated by Django 5.2.5 on 2025-09-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_vehiculo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='dominio',
            field=models.CharField(help_text='AA123BB o ABC123', max_length=10, unique=True, verbose_name='Dominio'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='dominio_remolque',
            field=models.CharField(blank=True, help_text='Opcional. AA123BB o ABC123', max_length=10, null=True, unique=True, verbose_name='Dominio remolque'),
        ),
    ]
