# Generated by Django 5.2.5 on 2025-09-18 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_vehiculo_dominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='ejes',
            field=models.PositiveIntegerField(default=5, help_text='Número de ejes que posee el vehículo', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de ejes'),
        ),
    ]
