# Generated by Django 5.2.5 on 2025-09-18 15:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0004_vehiculo_ejes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neumatico',
            fields=[
                ('idNeumatico', models.AutoField(db_column='idNeumatico', primary_key=True, serialize=False)),
                ('nroNeumatico', models.PositiveIntegerField(help_text='Número interno/posición del neumático en el vehículo', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nº de neumático')),
                ('montado', models.BooleanField(default=False, verbose_name='¿Montado en vehículo?')),
                ('km', models.PositiveIntegerField(default=0, help_text='Cantidad de km acumulados por el neumático', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilómetros recorridos')),
                ('vehiculo', models.ForeignKey(blank=True, db_column='idVehiculo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neumaticos', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Neumático',
                'verbose_name_plural': 'Neumáticos',
                'db_table': 'tablaNeumaticos',
                'ordering': ['idNeumatico'],
            },
        ),
        migrations.CreateModel(
            name='EstadoNeumatico',
            fields=[
                ('idEstadoNeumatico', models.AutoField(db_column='idEstadoNeumatico', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado de neumático',
                'verbose_name_plural': 'Estados de neumático',
                'db_table': 'estadoNeumaticos',
                'ordering': ['idEstadoNeumatico'],
            },
        ),
        migrations.CreateModel(
            name='TipoNeumatico',
            fields=[
                ('idTipo', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de neumático',
                'verbose_name_plural': 'Tipos de neumático',
                'db_table': 'tipoNeumatico',
                'ordering': ['idTipo'],
            },
        ),
        migrations.CreateModel(
            name='AlmacenNeumaticos',
            fields=[
                ('idNeumatico', models.OneToOneField(db_column='idNeumatico', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='almacen', serialize=False, to='neumaticos.neumatico', verbose_name='Neumático')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
            ],
            options={
                'verbose_name': 'Almacén de neumático',
                'verbose_name_plural': 'Almacén de neumáticos',
                'db_table': 'almacenNeumaticos',
                'ordering': ['fecha_ingreso'],
            },
        ),
        migrations.AddField(
            model_name='neumatico',
            name='estado',
            field=models.ForeignKey(db_column='idEstadoNeumatico', on_delete=django.db.models.deletion.PROTECT, to='neumaticos.estadoneumatico', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='neumatico',
            name='tipo',
            field=models.ForeignKey(blank=True, db_column='idTipoNeumatico', null=True, on_delete=django.db.models.deletion.PROTECT, to='neumaticos.tiponeumatico', verbose_name='Tipo de neumático'),
        ),
        migrations.AddConstraint(
            model_name='neumatico',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'nroNeumatico'), name='uq_vehiculo_nro_neumatico'),
        ),
    ]
