# Generated by Django 5.2.5 on 2025-10-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neumaticos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neumatico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='neumatico',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='neumatico',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
