# Generated by Django 5.2.5 on 2025-09-22 14:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0004_vehiculo_ejes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AceiteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.DecimalField(blank=True, decimal_places=2, help_text='Odómetro al momento del cambio (opcional).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fecha', models.DateField(db_index=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceite_caja', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Cambio de aceite (caja)',
                'verbose_name_plural': 'Cambios de aceite (caja)',
                'db_table': 'tablaAceiteCaja',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AceiteMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.DecimalField(blank=True, decimal_places=2, help_text='Odómetro al momento del cambio (opcional).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('filtros', models.BooleanField(default=False, help_text='¿Se cambiaron filtros?')),
                ('fecha', models.DateField(db_index=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceite_motor', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Cambio de aceite (motor)',
                'verbose_name_plural': 'Cambios de aceite (motor)',
                'db_table': 'tablaAceiteMotor',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
