# Generated by Django 5.2.5 on 2025-09-22 20:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aceitecaja',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterModelOptions(
            name='aceitemotor',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterField(
            model_name='aceitecaja',
            name='km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Km acumulados desde el último cambio de aceite de caja.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='aceitemotor',
            name='filtros',
            field=models.BooleanField(default=False, help_text='¿Se cambiaron filtros en este cambio?'),
        ),
        migrations.AlterField(
            model_name='aceitemotor',
            name='km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Km acumulados desde el último cambio de aceite de motor.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
