# Generated by Django 5.2.5 on 2025-09-30 15:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceite', '0002_alter_aceitecaja_options_alter_aceitemotor_options_and_more'),
        ('vehiculos', '0004_vehiculo_ejes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aceitemotor',
            name='vehiculo',
        ),
        migrations.CreateModel(
            name='Aceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('motor', 'Motor'), ('caja', 'Caja')], db_index=True, max_length=20)),
                ('viajes_km_acumulados_al_instalar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de km de viajes del vehículo al momento de instalar/cambiar.', max_digits=12)),
                ('km_acumulados', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vida_util_km', models.PositiveIntegerField(default=15000, help_text='Intervalo recomendado de cambio (km).')),
                ('ciclos', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('en_uso', 'En uso'), ('cambiado', 'Cambiado')], default='en_uso', max_length=20)),
                ('fecha_instalacion', models.DateField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Aceite',
                'verbose_name_plural': 'Aceites',
                'db_table': 'tablaAceite',
                'ordering': ['vehiculo_id', 'tipo', '-fecha_instalacion'],
            },
        ),
        migrations.CreateModel(
            name='AceiteCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('km_acumulados_al_cambio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('filtros_cambiados', models.BooleanField(default=False, help_text='Solo aplica a cambios de aceite de motor.')),
                ('aceite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='aceite.aceite')),
            ],
            options={
                'verbose_name': 'Cambio de aceite',
                'verbose_name_plural': 'Cambios de aceite',
                'db_table': 'tablaAceiteCambio',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='AceiteCaja',
        ),
        migrations.DeleteModel(
            name='AceiteMotor',
        ),
    ]
