# Generated by Django 5.2.5 on 2025-09-30 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceite', '0003_remove_aceitemotor_vehiculo_aceite_aceitecambio_and_more'),
        ('vehiculos', '0004_vehiculo_ejes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceite',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites', to='vehiculos.vehiculo'),
        ),
    ]
