# Generated by Django 5.2.5 on 2025-09-30 21:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceite', '0004_alter_aceite_vehiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aceite',
            options={'ordering': ['vehiculo_id', 'tipo', '-fecha_instalacion']},
        ),
        migrations.AlterModelOptions(
            name='aceitecambio',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='aceite',
            name='estado',
        ),
        migrations.AlterField(
            model_name='aceite',
            name='viajes_km_acumulados_al_instalar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='aceite',
            name='vida_util_km',
            field=models.PositiveIntegerField(default=30000),
        ),
        migrations.AlterField(
            model_name='aceitecambio',
            name='filtros_cambiados',
            field=models.BooleanField(default=False, help_text='Solo aplica a motor.'),
        ),
    ]
