# Generated by Django 5.2.5 on 2025-10-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aceite', '0005_alter_aceite_options_alter_aceitecambio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aceite',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='aceite',
            name='viajes_km_acumulados_al_instalar',
        ),
    ]
