# Generated by Django 5.2.5 on 2025-10-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aceite', '0006_remove_aceite_notas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aceitecambio',
            name='notas',
        ),
    ]
