# Generated by Django 5.2.5 on 2025-10-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceite', '0007_remove_aceitecambio_notas'),
        ('vehiculos', '0004_vehiculo_ejes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aceite',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'tipo'), name='uniq_aceite_vehiculo_tipo'),
        ),
    ]
