# Generated by Django 5.2.5 on 2025-10-09 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceite', '0008_aceite_uniq_aceite_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceite',
            name='fecha_instalacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
