# Generated by Django 5.2.5 on 2025-08-27 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='divisa',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='lugar',
        ),
        migrations.DeleteModel(
            name='Divisa',
        ),
        migrations.DeleteModel(
            name='Lugares',
        ),
    ]
