# Generated by Django 5.2.5 on 2025-08-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_divisa_remove_cliente_lugar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='divisa',
            field=models.CharField(default='peso', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(default='Indicar', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
