# Generated by Django 5.2.5 on 2025-08-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_divisa_cliente_localidad_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='tablaClientes',
        ),
    ]
