# Generated by Django 5.2.5 on 2025-08-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Cliente'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default='correo@ejemplo.com', max_length=50),
            preserve_default=False,
        ),
    ]
