# Generated by Django 5.2.5 on 2025-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_options_cliente_correo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='divisa',
            field=models.CharField(choices=[('Peso', 'Peso'), ('Real', 'Real'), ('Dolar', 'Dolar')], default='Peso', max_length=50),
        ),
    ]
