# Generated by Django 5.2.5 on 2025-09-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_options'),
        ('clientes', '0006_alter_cliente_options_alter_cliente_correo_and_more'),
    ]

    operations = [
    ]
