# Generated by Django 5.2.5 on 2025-11-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_options_remove_cliente_divisa_and_more'),
        ('ubicaciones', '0002_localidad_lat_localidad_lng_pais_lat_pais_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('correo',), name='unique_active_correo'),
        ),
    ]
