# Generated by Django 5.2.5 on 2025-08-31 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0002_vehiculo_anio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreApellido', models.CharField(max_length=120, verbose_name='Nombre y Apellido')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('dominio', models.CharField(max_length=10, verbose_name='Dominio')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conductores', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['id'],
            },
        ),
    ]
