# Generated by Django 5.2.5 on 2025-09-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreApellido', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('dominio', models.CharField(help_text='Ej: AA123BB o ABC123', max_length=10, unique=True, verbose_name='Dominio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'tablaConductores',
                'ordering': ['id'],
            },
        ),
    ]
