# Generated by Django 5.2.5 on 2025-11-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
        ('vehiculos', '0004_vehiculo_ejes'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='dni',
            field=models.CharField(max_length=10, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='dominio',
            field=models.CharField(help_text='Ej: AA123BB o ABC123', max_length=10, verbose_name='Dominio'),
        ),
        migrations.AddConstraint(
            model_name='conductor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('dni',), name='unique_active_dni'),
        ),
        migrations.AddConstraint(
            model_name='conductor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('dominio',), name='unique_active_dominio'),
        ),
    ]
